_merge: deep

# Image
image:
  desktop: "1296x"
projects:
  thumbnail:
    desktop: "306x230"
    mobile: "315x236"
  images:
    desktop: "x402"
    mobile: "x402"
blocks:
  informations:
    image:
      ratio: .75
  figure:
    full:
      ratio: .375

# JS
carousel: true
map: false
bootstrap:
  modal: false

# Admin
admin:

  i18n:
    default_locale: fr

  # Collections
  collections:
    
    projects:
      fields:
        - draft
        - date
        - title_page
        - description
        - relation:
            collection: projects_types
            multiple: true
        - relation:
            collection: projects_tags
            multiple: true
        - relation:
            collection: projects_clients
            multiple: true
        - relation:
            collection: projects_talents
            multiple: true
        - featured_image
        - video_embed
        - datas
        - images
      summary: "{{year}} - {{title | upper}} - {{projects_clients.0}} {{projects_clients.1}}"
      
    projects_clients:
      enable: true

    projects_talents:
      enable: true
      fields:
        - draft
        - title_page
        - description
        - featured_image
    
  # blocks
  blocks:

    enable:
      - editorial
      - datas 
      - informations 
      - figure
      - logos
      - paragraph
      - selected
      - video
    
    editorial:
      notes: false
      fields:
        - direction
        - title
        - text_markdown
        - ctas
        - image
    
    paragraph:
      notes: false
      fields:
        - title
        - text_markdown
        - grid
    
    video:
      fields:
        - heading
        - video_embed
        - grid

  # fields
  fields:
    hero:
      fields:
        - title
        - ctas
        - image
        - video_embed
    video_platform:
      options:
        - vimeo
        - youtube
    
  # Remove shortcodes
  shortcodes:
    enable: false